version: "3.8"

services:
  app:
    container_name: hrs_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${API_PORT}:${API_PORT}
      - "3444:3444"
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - sqlserver
    volumes:
      - ./src/logs:/usr/src/app/src/logs

  sqlserver:
    container_name: hrs_db_sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - "SA_PASSWORD:${SA_PASSWORD}"
      - "ACCEPT_EULA:${ACCEPT_EULA}"
    volumes:
      - sqldata:/var/opt/mssql
    restart: always
    networks:
      - backend
    env_file:
      - .env

volumes:
  sqldata:
    driver: local

networks:
  backend:
    driver: bridge
