version: '3'

services:
  app:
    container_name: hrs-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${API_PORT}:${API_PORT}
      - "3444:3444"
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
    driver: bridge